# Generated by Django 5.1.4 on 2025-02-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Order Issue', 'Order Issue'), ('Payment Issue', 'Payment Issue'), ('Technical', 'Technical'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('Message', models.TextField(default='Default message', max_length=3000)),
                ('Response', models.TextField(blank=True, null=True)),
                ('Response_Time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
