version: '3.9'

services:
  db:
    image: docker.arvancloud.ir/postgres:15
    container_name: postgres_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laklak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1162m
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_container
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: laklak_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1162m
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

volumes:
  postgres_data:
