# Generated by Django 5.1.4 on 2025-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('service', 'Service'), ('sanitary', 'Sanitary'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50),
        ),
    ]
