# Generated by Django 5.1.4 on 2025-03-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
