# Generated by Django 5.1.4 on 2025-02-06 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='score_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='score_sum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='target_group',
            field=models.CharField(choices=[('pregnance', 'Pregnant Mothers'), ('less_6', 'Infants to 6 Months'), ('less_12', 'Infants to One Year'), ('less_24', 'Infants to Two Years')], null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
