# Generated by Django 5.1.4 on 2025-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_package_creation_date_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='target_group',
            field=models.CharField(choices=[('pregnants', 'Pregnant Mothers'), ('less_6', 'Infants to 6 Months'), ('less_12', 'Infants to One Year'), ('less_24', 'Infants to Two Years')], null=True),
        ),
    ]
