name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3
      
      - name: Set up Python Environment
        uses: actions/setup-python@v3
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          python manage.py test


      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Backend  
            git pull
            sudo docker-compose down 
            sudo docker-compose up --build -d 
