name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Setup SSH tunnel
        run: |
          # Install sshpass and netcat
          sudo apt-get install -y sshpass netcat-openbsd

          # Create SSH config
          mkdir -p ~/.ssh
          echo "Host target
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            Port 22
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            ServerAliveInterval 60
            ServerAliveCountMax 10
            ConnectTimeout 180" > ~/.ssh/config
            
          # Test connection with debug output
          echo "Testing connection with debug..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -v target "echo 'Connection test'"

      - name: Deploy
        if: success()
        env:
          DEPLOY_CMD: |
            cd ~/Backend
            git pull
            sudo docker-compose down
            sudo docker-compose up --build -d
        run: |
          # Try multiple times with increasing delays
          for i in 1 2 3; do
            echo "Attempt $i..."
            sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -v target "${DEPLOY_CMD}" && break || {
              echo "Attempt $i failed. Waiting..."
              sleep $((i * 10))
            }
          done
