name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "Testing SSH connection..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ~/Backend && \
            git pull && \
            sudo docker-compose down && \
            sudo docker-compose up --build -d
          '
