name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Network Diagnostics
        run: |
          echo "Testing connection to server..."
          echo "Running nslookup..."
          nslookup ${{ secrets.SSH_HOST }}
          
          echo "Running ping test..."
          ping -c 4 ${{ secrets.SSH_HOST }}
          
          echo "Testing port 22..."
          nc -zv -w 5 ${{ secrets.SSH_HOST }} 22

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          timeout: 60s # Increased timeout
          command_timeout: 20m # Increased command timeout
          script: |
            cd ~/Backend  
            git pull
            sudo docker-compose down 
            sudo docker-compose up --build -d
