name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Setup SSH and Debug
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          # Enable SSH debugging
          echo "Setting up SSH debugging..."
          echo "Host *" > ~/.ssh/config
          echo "  LogLevel DEBUG3" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          
      - name: Test SSH connection with verbose output
        run: |
          echo "Testing SSH connection..."
          ssh -v -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Connection successful'"

      - name: SSH and Deploy
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Backend  
            git pull
            sudo docker-compose down 
            sudo docker-compose up --build -d
