name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Network Diagnostics
        run: |
          echo "Running network diagnostics..."
          echo "Current IP: $(curl -s https://api.ipify.org)"
          
          # Try various timeout values
          for timeout in 5 10 30; do
            echo "Testing connection with ${timeout}s timeout..."
            nc -zv -w $timeout ${{ secrets.SSH_HOST }} 22 && break || echo "Failed with ${timeout}s timeout"
            sleep 2
          done

      - name: Deploy with alternative method
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: "20m"
          script: |
            cd ~/Backend  
            git pull
            sudo docker-compose down 
            sudo docker-compose up --build -d
