name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Backend  
            git pull
            docker-compose down 
            docker-compose up --build -d 
            sudo docker-compose down 
            sudo docker-compose up --build -d 
