name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codes
        uses: actions/checkout@v3

      - name: Advanced Connection Test
        run: |
          echo "Current IP: $(curl -s https://api.ipify.org)"
          echo "Testing TCP connection..."
          
          # Try basic TCP connection with netcat
          echo "NC test with timeout 5:"
          nc -zvw5 ${{ secrets.SSH_HOST }} 22
          
          # Try multiple connection methods
          echo "Testing SSH connection methods..."
          
          # Method 1: Direct sshpass
          echo "Method 1: sshpass"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "test1"' || echo "Method 1 failed"
          
          # Method 2: Using different SSH options
          echo "Method 2: Custom SSH options"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh \
            -o ConnectTimeout=10 \
            -o StrictHostKeyChecking=no \
            -o PreferredAuthentications=password \
            -o PubkeyAuthentication=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "test2"' || echo "Method 2 failed"

      - name: Deploy if connection succeeds
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/Backend  
            git pull
            sudo docker-compose down 
            sudo docker-compose up --build -d
